










model:
  TextEncoder:
    class_name: "game.rlearning.net.state_space.jina_text_encoder.JinaTextEncoder"
    model_name: "jinaai/jina-embeddings-v5-text-small"
    local_model_path: "models/jina-embeddings-v5-text-small"
    cache_dir: "models"
    task: "text-matching"
    truncate_dim: 128
    normalize: True
    trust_remote_code: True
    local_files_only: False
    lazy_load: True
    trainable: True