train_config:
  - game/rlearning/config/agents/pair_excercise/v1/05_blue_flash_flying.yaml
  - game/rlearning/config/agents/pair_excercise/v1/13_red_disruption.yaml
  - game/rlearning/config/agents/pair_excercise/v1/19_green_graveyard_value.yaml
  - game/rlearning/config/agents/pair_excercise/v1/25_white_angel_control.yaml
  - game/rlearning/config/agents/pair_excercise/v1/31_black_lifedrain_control.yaml

env: "game.rlearning.parallel_env.training_parallel_env_pair_exercise.Parallel_Env_Pair_Exercise"
info_communication: "game.rlearning.communicate.training_parallel_room.Info_Communication"
room: "game.rlearning.trainingRoom.training_parallel_room.Multi_Agent_Parallel_Room"
inference:
  max_batch_size: 32
  max_wait_ms: 5
  max_cached_policies: 8
rollout_torch_threads: 1
num_worker: 5
