version: '3.8'

services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 20040723Caesar  # 设置 root 用户的密码为 20040723Caesar
      MYSQL_DATABASE: Magic_fan_made  # 创建的数据库名称
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/magic_backup.sql:/docker-entrypoint-initdb.d/magic_backup.sql  # 挂载 data.sql 文件

  web:
    image: registry.cn-shanghai.aliyuncs.com/magic_fan_made/server_magic
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_AIOURL: mysql+aiomysql://root:20040723Caesar@db/Magic_fan_made  # 使用  作为密码
      DATABASE_PYURL: mysql+pymysql://root:20040723Caesar@db/Magic_fan_made  # 使用  作为密码
    cap_add:
      - NET_BIND_SERVICE

volumes:
  db_data:
