
###########################
# Common
###########################

log_dir: "ppo/ppo_growing_lstm_n02_v01"
restore_step: 0
new_version: True
new_history: True
history_attack: True
reward_type: "reward_mana"
sort_method: "score_tap"
#------------------------------------
action_history_length: 15
cards: "Blightsteel Colossus+Creature+4|Essence Channeler+Creature+14|Forest+Land+15|Sylvan Harmonist+Creature+4|Chronostrider+Creature+4|Thornroot Druid+Creature+4"
treasures:
- "pytreasures.Lucky_Clover_Pin.model.Lucky_Clover_Pin"
- "pytreasures.Endless_Grimoire.model.Endless_Grimoire"
#------------------------------------


###########################
#  Train 
###########################
seed: 1247
max_store: 1024
#------------------------------------
dataset_class_name: "game.rlearning.datasets.ppo_agent_lstm_attack.PPOAgentDataset"
dataloader:
  batch_size: 32
  num_workers: 0

dataset_multiple: 10


#------------------------------------
trainer: "game.rlearning.module.ppo_agent_lstm_attack.PPOTrainer"

w_val_loss: 0.5
w_act_loss: 0.5
w_kl_loss: 0.1
w_entropy_loss: 0.0

ppo:
  gamma: 0.99
  lambd: 0.95
  clip_para: 0.2
  



optimizer:
  learning_rate: 2.0e-6
  betas: [0.8, 0.99]
  eps: 1.0e-9 
  grad_clip_thresh: 1.0
  n_warmup_steps: 0

scheduler:
  step_size: 200
  gamma: 0.998

reset_epoch: False
reset_learning_rate: True
moving_average_beta: 0

#------------------------------------
total_step: 200000
log_step: 20
eval_step: 2000
synthesis_step: 2000
synthesis_items: 20
save_step: 2000
epochs: 5
n_epoch: 15
###########################
#  Model 
###########################
shared_card_cfg: &shared_card_cfg
  max_card_id: 100
  max_card_type: 4

  card_special_types_len: 20
  card_cost_len: 6
  num_cards: 10

  max_mana: 20


  id_dim: 32
  type_dim: 16
  cat_emb_dim: 16
  mana_dim: 16
  cont_hidden: 32
  card_embed_dim: 128
  attention_whole_card: False
  use_attn_pool: False
  
  



model:

  
  HeroEmbedSelf:
    class_name: 'game.rlearning.net.embed.HeroEmbed'
    len_life: 21
    embed_dim: 16
    

  HeroEmbedOppo:
    class_name: 'game.rlearning.net.embed.HeroEmbed'
    len_life: 21
    embed_dim: 16

  ManaEmbed:
    class_name: 'game.rlearning.net.embed.ManaEmbed'
    len_mana: 5
    embed_dim: 16
    max_mana: 20

  CardsHandEmbed:
    class_name: 'game.rlearning.net.embed.HandEmbedNew'
    <<: *shared_card_cfg
    card_hand_dim: 40


  CardsBoardEmbedSelf:
    class_name: 'game.rlearning.net.embed.BoardEmbedNew'
    <<: *shared_card_cfg
    combat_dim: 4


  CardsBoardEmbedOppo:
    class_name: 'game.rlearning.net.embed.BoardEmbed'
    <<: *shared_card_cfg


  AttackerEmbed:
    class_name: 'game.rlearning.net.embed.CardBoardEmbed'
    <<: *shared_card_cfg

  ActionEmbed:
    class_name: 'game.rlearning.net.embed.ActionEmbed'
    action_dim: 1342
    action_embed_dim: 128
    is_g: False

  Dense:
    class_name: 'game.rlearning.net.baseNets.Dense'
    d_in: 16
    d_out: 560
    is_g: False

  HistoryEmbed:
    class_name: 'game.rlearning.net.embed.HistoryEmbed'
    history_dim: 43
    history_embed_dim: 128
    

  Actor:
    class_name: 'game.rlearning.net.ppo.Actor'
    input_dim: 1072
    hidden_dim: 512
    output_dim: 1342
    deep: 5
  Critic:
    class_name: 'game.rlearning.net.ppo.Critic'
    input_dim: 1072
    hidden_dim: 512
    output_dim: 1
    deep: 5
  

    
