
###########################
# Common
###########################

log_dir: "dqn/rainbowdqn_white_lstm_n02_v01"
restore_step: 0
new_version: True
#------------------------------------
action_history_length: 10
cards: "Elite Squire+Creature+2|Celestial Skyweaver+Creature+2|Pious Courser+Creature+3|Ironclad Crusader+Creature+2|Sunlit Priestess+Creature+3|Apocalypse Riders+Sorcery+4|Call to Unity+Sorcery+4|Angelic Blessing+Sorcery+2|Righteous Conviction+Sorcery+2|Spectral Embrace+Sorcery+3|Celestial Convergence+Instant+1|Avenging Light+Instant+1|Plains+Land+15"

#------------------------------------


###########################
#  Train 
###########################
seed: 1247
max_store: 1024
#------------------------------------
dataset_class_name: "game.rlearning.datasets.rainbow_dqn.RainbowDQNDataset"
dataloader:
  batch_size: 32
  num_workers: 0
  beta: 0.4
  shuffle: False

dataset_multiple: 10


#------------------------------------
trainer: "game.rlearning.module.rainbow_dqn.RainbowDQNTrainer"

w_q_loss: 1.0


rainbowdqn:
  tree_capacity: 100000
  gamma: 0.99
  lambd: 0.95
  alpha: 0.6
  max_priority: 1.0
  nstep: 3
  v_min: -10
  v_max: 10
  atom_size: 51
  



optimizer:
  learning_rate: 1.0e-4  
  betas: [0.8, 0.99]
  eps: 1.0e-9 
  grad_clip_thresh: 1.0
  n_warmup_steps: 0
  

scheduler:
  step_size: 200
  gamma: 0.998

reset_epoch: False
reset_learning_rate: True
moving_average_beta: 0

#------------------------------------
total_step: 500000
log_step: 20
eval_step: 2000
synthesis_step: 2000
synthesis_items: 20
save_step: 2000
epochs: 5
n_epoch: 15
target_update_interval: 1000
###########################
#  Model 
###########################
shared_card_cfg: &shared_card_cfg
  max_card_id: 100
  max_card_type: 4

  card_special_types_len: 20
  card_cost_len: 6
  num_cards: 10

  max_mana: 20


  id_dim: 32
  type_dim: 16
  cat_emb_dim: 16
  mana_dim: 16
  cont_hidden: 32
  card_embed_dim: 128
  
  
action_dim: &action_dim 1342


model:

  
  HeroEmbedSelf:
    class_name: 'game.rlearning.net.embed.HeroEmbed'
    len_life: 21
    embed_dim: 16
    

  HeroEmbedOppo:
    class_name: 'game.rlearning.net.embed.HeroEmbed'
    len_life: 21
    embed_dim: 16

  ManaEmbed:
    class_name: 'game.rlearning.net.embed.ManaEmbed'
    len_mana: 5
    embed_dim: 16
    max_mana: 20

  CardsHandEmbed:
    class_name: 'game.rlearning.net.embed.HandEmbedNew'
    <<: *shared_card_cfg
    card_hand_dim: 160


  CardsBoardEmbedSelf:
    class_name: 'game.rlearning.net.embed.BoardEmbed'
    <<: *shared_card_cfg


  CardsBoardEmbedOppo:
    class_name: 'game.rlearning.net.embed.BoardEmbed'
    <<: *shared_card_cfg


  AttackerEmbed:
    class_name: 'game.rlearning.net.embed.CardBoardEmbed'
    <<: *shared_card_cfg

  ActionEmbed:
    class_name: 'game.rlearning.net.embed.ActionEmbed'
    action_dim:  *action_dim
    action_embed_dim: 128
    is_g: False

  Dense:
    class_name: 'game.rlearning.net.baseNets.Dense'
    d_in: 16
    d_out: 560
    is_g: False

  HistoryEmbed:
    class_name: 'game.rlearning.net.embed.HistoryEmbed'
    history_dim: 61
    history_embed_dim: 128
    

  Online:
    class_name: 'game.rlearning.net.rainbow_dqn.RainbowMLP'
    input_dim: 688
    hidden_dim: 512
    atom_size: 51
    output_dim:  *action_dim
    deep: 3
  Target:
    class_name: 'game.rlearning.net.rainbow_dqn.RainbowMLP'
    input_dim: 688
    hidden_dim: 512
    atom_size: 51
    output_dim:  *action_dim
    deep: 3
  

    
